//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetailsTbl
    {
        public int Id { get; set; }
        public int ShippingDetailsID { get; set; }
        public int OrderID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public int PostCode { get; set; }
        public string OrderNote { get; set; }
        public bool status { get; set; }
        public System.DateTime rts { get; set; }
    }
}
