//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbdeeptiartsEntities : DbContext
    {
        public dbdeeptiartsEntities()
            : base("name=dbdeeptiartsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutDetailsTbl> AboutDetailsTbls { get; set; }
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<BillingDetailsTbl> BillingDetailsTbls { get; set; }
        public virtual DbSet<CartTbl> CartTbls { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<ContactEnquiryTbl> ContactEnquiryTbls { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<FrameTbl> FrameTbls { get; set; }
        public virtual DbSet<MainCategoryTbl> MainCategoryTbls { get; set; }
        public virtual DbSet<OrderDetailsTbl> OrderDetailsTbls { get; set; }
        public virtual DbSet<OrderTbl> OrderTbls { get; set; }
        public virtual DbSet<OurTeamTbl> OurTeamTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<RegisteredUsersTbl> RegisteredUsersTbls { get; set; }
        public virtual DbSet<ReviewTable> ReviewTables { get; set; }
        public virtual DbSet<ShippingDetailsTbl> ShippingDetailsTbls { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<SubCategoryTbl> SubCategoryTbls { get; set; }
        public virtual DbSet<WishlistTbl> WishlistTbls { get; set; }
        public virtual DbSet<ProductEnquiryTbl> ProductEnquiryTbls { get; set; }
        public virtual DbSet<PrebookingTbl> PrebookingTbls { get; set; }
        public virtual DbSet<HomeBannerSliderTbl> HomeBannerSliderTbls { get; set; }
    }
}
