//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTbl
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public int BillingID { get; set; }
        public int ShippingID { get; set; }
        public int CustomerID { get; set; }
        public int TotalAmount { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime OrderDateTime { get; set; }
    }
}
