//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurTeamTbl
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string about { get; set; }
        public string image { get; set; }
        public string testimonialReview { get; set; }
    }
}
