//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        public int Id { get; set; }
        public int CId { get; set; }
        public string CatName { get; set; }
        public int SCId { get; set; }
        public string SubcatName { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Details { get; set; }
        public int Price { get; set; }
        public bool status { get; set; }
        public System.DateTime rts { get; set; }
        public Nullable<int> GrossPrice { get; set; }
    }
}
