//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewTable
    {
        public int Id { get; set; }
        public int productid { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public int rating { get; set; }
        public string profilephoto { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public bool status { get; set; }
        public System.DateTime rts { get; set; }
    }
}
