//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int state_id { get; set; }
        public string state_title { get; set; }
        public string state_description { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
