//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeptiArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryTbl
    {
        public int Id { get; set; }
        public int CID { get; set; }
        public string CatName { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryImage { get; set; }
        public bool status { get; set; }
    }
}
